### ISSUE TITLE
Duplicating the pixman package

### ISSUE THREAD

**Issue by impocode** [hyprwm/aur#3]
In files PKGBUILD, PKGBUILD-bin and PKGBUILD-git the pixman package is duplicated. For example, line [21](https://github.com/hyprwm/aur/blob/main/PKGBUILD#L21) and line [31](https://github.com/hyprwm/aur/blob/main/PKGBUILD#L31)

**Comment by alba4k** [comment]
This repo is basically unmaintained, just use the pkgbuilds you find on the aur for everythinf
